### ISSUE TITLE
Difficulties in using warp-cloudflare-gui-rust

### ISSUE THREAD

**Issue by bestperson-free** [progzone122/warp-cloudflare-gui-rust#15]
Hello, maybe it’s [coincident](https://community.cloudflare.com/t/after-updating-to-2024-12-554-windows-warp-service-is-no-longer-available/750216/5) , but I still couldn't run the program. Now this message appears, although WAP is connected and there is Internet, but warpgui is used. What should be done to fix it, or is it better to wait against the backdrop of a wave of failures?)
```
sudo systemctl enable warp-svc.service --now  
```

```
Please accept the WARP Terms of Service by running this command in a TTY or by passing the --accept-tos flag.
```
![Снимок экрана_20241221_170533](https://github.com/user-attachments/assets/1e95222d-3a13-4b24-8e20-261903d5de1a)

**Comment by progzone122** [comment]
Give more information.
Name of your distribution, version of warp-cli?
If you have arch-based, have you tried uninstalling and disabling warp-cli and just installing the package from AUR (it will automatically install the right version of warp-cloudflare-bin)
Have you tried the AppImage package?

**Comment by progzone122** [comment]
On several Arch Linux systems I have everything is fine

**Comment by progzone122** [comment]
![изображение](https://github.com/user-attachments/assets/43b00ffc-ce13-45c9-8a22-018bdd39cf21)

**Comment by bestperson-free** [comment]
Sorry, I have Manjaro, version 03-02.1, I built the AUR package
https://drive.google.com/file/d/1bI-pKPEWiS2lsnkhuBMBzljm1mQZRT9t/view?usp=sharing
I looked at the code on your page but I don't see the AppImage package, please share the link. Thank you

**Comment by bestperson-free** [comment]
Somehow, miraculously, the program came to life, today I turned on the computer, Warp started, as always, automatically, and connected. After which I launched warp-cloudflare-gui-rust and simply showed that it was connected). Sorry to bother you, thanks for your attention
![Снимок экрана_20241222_181017](https://github.com/user-attachments/assets/b308face-bc21-4a57-9deb-96508f1f0f1d)

**Comment by bestperson-free** [comment]
It would be nice to add to the program as done in Android, for example the ability to enable DOH for example and
DNS only mode via DoH: 
warp-cli mode doh
WARP with DoH: 
warp-cli mode warp+doh
Family mode off: 
warp-cli dns families off
Anti-malware: 
warp-cli dns families malware
Malware and adult content: warp-cli dns families full
warp-cli --help
That would be cool. Thank you

**Comment by dotaziz** [comment]
Running `warp-cli connect` provides an interface to accept the terms of service.
