### ISSUE TITLE
Can we please have app icon from dependency and not water mark

### ISSUE THREAD

**Issue by DioKyrie** [progzone122/warp-cloudflare-gui-rust#3]
so 
  install -Dm644 "$srcdir/watermark.png" "$pkgdir/usr/share/icons/hicolor/48x48/apps/warp-gui.png"  
  Makes this icon on right:
  
![image](https://github.com/user-attachments/assets/255f4cf0-53b0-4e69-baf9-ebb390cce221)

It does not look right on Gnome DE.
But warp-gui installs cloudflare-warp-bin
Which has a good looking icon on left. Can you use that icon as app icon.
Or at least fix current icon to look good on all scales of icon.
As 48x48 is not good for Gnome DE.

Like this
Icon=zero-trust-orange

**Comment by DioKyrie** [comment]
Or make .svg file so it will scale to any size

**Comment by progzone122** [comment]
That's a good idea! Thanks for the suggestion to use the zero-trust-orange icon

**Comment by progzone122** [comment]
Improved!
